### ISSUE TITLE
Update config-perso/install_config.sh

### ISSUE THREAD

**Issue by JosephLucas** [oryxr/config-perso#1]
Salut Pierre,

J'ai installé ta configuration de vim et ça marche très bien :)
Durant l'installation, j'ai pensé à quelques améliorations de ton script d'installation que tu trouveras si dessous. 

A très bientôt,

Joseph
# ! /bin/sh

ln -s ${PWD}/vim/vimrc ${HOME}/.vimrc
mkdir ${HOME}/.vim/
ln -s ${PWD}vim/config/ ${HOME}/.vim/
mkdir ${HOME}/.vim/bundle
git clone https://github.com/gmarik/Vundle.vim.git ${HOME}/.vim/bundle/Vundle.vim
wget https://www.languagetool.org/download/LanguageTool-2.6.zip
mkdir ${HOME}/.vim/progExt
unzip LanguageTool-2.6.zip
mv LanguageTool-2.6 ${HOME}/.vim/progExt/
rm -r LanguageTool-2.6.zip
vim +PluginInstall +qall
mkdir -p ${HOME}/.vim/colors && cd ${HOME}/.vim/colors
wget -O wombat256mod.vim http://www.vim.org/scripts/download_script.php?src_id=13400

**Comment by JosephLucas** [comment]
En fait la ligne:

ln -s vim/config/ ~/.vim/

ne me semble pas tout à fait exacte, je ne suis pas sûr que ce soit vraiment ce que tu veux faire, car il n'y a pas une prise en compte des dossiers : 

config-perso / vim / spell /
config-perso / vim / view /
config-perso / vim / colors /
config-perso / vim / syntax /

J'ai forké ton dépot pour le modifier à ma manière. Tu peux trouver mon fork ici:
https://github.com/JosephLucas/config-perso

Joseph

**Comment by oryxr** [comment]
Merci,  j'ai mis à jour les motifs qui m'intéressais. 
A plus
